package activos.logic;
// Generated 19/03/2019 08:02:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer idFuncionario;
     private Dependencia dependencia;
     private String cedula;
     private String dependencia_1;
     private Set biens = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(Dependencia dependencia, String cedula, String dependencia_1) {
        this.dependencia = dependencia;
        this.cedula = cedula;
        this.dependencia_1 = dependencia_1;
    }
    public Funcionario(Dependencia dependencia, String cedula, String dependencia_1, Set biens) {
       this.dependencia = dependencia;
       this.cedula = cedula;
       this.dependencia_1 = dependencia_1;
       this.biens = biens;
    }
   
    public Integer getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(Integer idFuncionario) {
        this.idFuncionario = idFuncionario;
    }
    public Dependencia getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Dependencia dependencia) {
        this.dependencia = dependencia;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getDependencia_1() {
        return this.dependencia_1;
    }
    
    public void setDependencia_1(String dependencia_1) {
        this.dependencia_1 = dependencia_1;
    }
    public Set getBiens() {
        return this.biens;
    }
    
    public void setBiens(Set biens) {
        this.biens = biens;
    }




}


