package activos.logic;
// Generated 19/03/2019 08:02:16 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud  implements java.io.Serializable {


     private Integer idSolicitud;
     private Dependencia dependencia;
     private String estado;
     private String comprobante;
     private String fecha;
     private String tipo;
     private String rasonRechazo;
     private String dependecia;
     private String registrador;
     private Set biens = new HashSet(0);

    public Solicitud() {
    }

	
    public Solicitud(Dependencia dependencia, String estado, String comprobante, String fecha, String tipo, String dependecia, String registrador) {
        this.dependencia = dependencia;
        this.estado = estado;
        this.comprobante = comprobante;
        this.fecha = fecha;
        this.tipo = tipo;
        this.dependecia = dependecia;
        this.registrador = registrador;
    }
    public Solicitud(Dependencia dependencia, String estado, String comprobante, String fecha, String tipo, String rasonRechazo, String dependecia, String registrador, Set biens) {
       this.dependencia = dependencia;
       this.estado = estado;
       this.comprobante = comprobante;
       this.fecha = fecha;
       this.tipo = tipo;
       this.rasonRechazo = rasonRechazo;
       this.dependecia = dependecia;
       this.registrador = registrador;
       this.biens = biens;
    }
   
    public Integer getIdSolicitud() {
        return this.idSolicitud;
    }
    
    public void setIdSolicitud(Integer idSolicitud) {
        this.idSolicitud = idSolicitud;
    }
    public Dependencia getDependencia() {
        return this.dependencia;
    }
    
    public void setDependencia(Dependencia dependencia) {
        this.dependencia = dependencia;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getComprobante() {
        return this.comprobante;
    }
    
    public void setComprobante(String comprobante) {
        this.comprobante = comprobante;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getRasonRechazo() {
        return this.rasonRechazo;
    }
    
    public void setRasonRechazo(String rasonRechazo) {
        this.rasonRechazo = rasonRechazo;
    }
    public String getDependecia() {
        return this.dependecia;
    }
    
    public void setDependecia(String dependecia) {
        this.dependecia = dependecia;
    }
    public String getRegistrador() {
        return this.registrador;
    }
    
    public void setRegistrador(String registrador) {
        this.registrador = registrador;
    }
    public Set getBiens() {
        return this.biens;
    }
    
    public void setBiens(Set biens) {
        this.biens = biens;
    }




}


